#!/usr/bin/env bash                                                              
                                                                                                                
                                                                                                                
ln -s `pwd`/bashrc $HOME/.bashrc                                                     
ln -s `pwd`/bash $HOME/.bash  

